<a href="https://colab.research.google.com/github/HalyshAnton/IT-Step-Pyton-AI/blob/main/module2/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [83]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [84]:
array = np.arange(1, 13)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть результат

In [85]:
matrix = array.reshape(-1, 4)

matrix = matrix.astype(np.float32)

print("\nMatrix with 4 columns and dtype float32:")
print(matrix)


Matrix with 4 columns and dtype float32:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


# Завдання 3
Створіть наступні матриці 8х8

In [86]:
# за замовчуванням всюди нулі
matrix = np.zeros((8, 8), dtype=int)
print("Original 8x8 matrix:")
print(matrix)

Original 8x8 matrix:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [87]:
# одиниця в рядку 2 стовпчик 3

matrix[1,2] = 1

print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [88]:
# рядок 3 з одиниць
matrix[2, :] = 1
print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [89]:
# стовпчик 2 з одиниць
matrix[:, 1] = 1
print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]]


In [90]:
# рядки з 2 по 4 з одиниць
matrix[1:4, :] = 1
print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [91]:
# стовпчики 3 і 4 з одиниць
matrix[:, 2:4] = 1
print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]]


In [92]:
# ділянка між рядками 1,4 та стовпчиками 2,4
matrix[1:4, 2:4] = 1
print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [93]:
# кожен непарний рядок
matrix[::2, :] = 1
print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]]


In [94]:
# кожен парний стовпчик
matrix[:, ::2] = 1
print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]


In [95]:
# рядки 4,5 та стовпчики 4,5
matrix[3:5, 3:5] = 1
print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [96]:
# шахматний порядок
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)
matrix = np.zeros((8, 8), dtype=int)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [97]:
# діагональ
np.fill_diagonal(matrix, 1)

print("Final 8x8 matrix:")
print(matrix)

Final 8x8 matrix:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


# Завдання 4

Створіть випадкову матрицю 4х3. Замініть усі значення менші за середнє арифметичне на -1

In [98]:
matrix = np.random.rand(4, 3)
print("Original matrix:")
print(matrix)

mean_value = matrix.mean()
print("\nMean value:", mean_value)

matrix[matrix < mean_value] = -1

print("\nModified matrix:")
print(matrix)

Original matrix:
[[0.92407267 0.00838423 0.08195261]
 [0.20831823 0.13889972 0.29231854]
 [0.89349839 0.29603897 0.07339923]
 [0.63785574 0.72550891 0.24900379]]

Mean value: 0.37743758606789185

Modified matrix:
[[ 0.92407267 -1.         -1.        ]
 [-1.         -1.         -1.        ]
 [ 0.89349839 -1.         -1.        ]
 [ 0.63785574  0.72550891 -1.        ]]


# Завдання 5
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [99]:
matrix = np.random.randint(1, 11, size=(4, 3))
print("Original matrix:")
print(matrix)

column_sums = matrix.sum(axis=0)
print("\nColumn sums:")
print(column_sums)

row_sums = matrix.sum(axis=1)
print("\nRow sums:")
print(row_sums)

total_sum = matrix.sum()
print("\nTotal sum:")
print(total_sum)

Original matrix:
[[ 1  3  9]
 [ 7  6  8]
 [ 8  3  1]
 [ 7 10  5]]

Column sums:
[23 22 23]

Row sums:
[13 21 12 22]

Total sum:
68


# Завдання 6
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [100]:
row_max = matrix.max(axis=1, keepdims=True)

adjusted_matrix = matrix - row_max

print("Original matrix:")
print(matrix)

print("\nMax values row:")
print(row_max)

print("\nMatrix after subtracting:")
print(adjusted_matrix)

Original matrix:
[[ 1  3  9]
 [ 7  6  8]
 [ 8  3  1]
 [ 7 10  5]]

Max values row:
[[ 9]
 [ 8]
 [ 8]
 [10]]

Matrix after subtracting:
[[-8 -6  0]
 [-1 -2  0]
 [ 0 -5 -7]
 [-3  0 -5]]


# Завдання 7
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

In [101]:
weights = np.array([5, 10, 25, 40])

counts = np.array([20, 5, 10, 4])

total_weight = np.sum(weights * counts)

print("Total cargo weight:", total_weight, "tons")

Total cargo weight: 560 tons


# Завдання 8
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.

In [102]:
# [дрібний, малий, середній, великий]
ships = np.array([
    [20,  5, 10,  4],
    [10,  2,  5,  1],
    [30, 10,  8,  2],
    [15,  3, 12,  6]
])


total_weights = np.sum(ships * weights, axis=1)
for i, weight in enumerate(total_weights, 1):
    print(f"Ship {i}: {weight} tons")

Ship 1: 560 tons
Ship 2: 235 tons
Ship 3: 530 tons
Ship 4: 645 tons
